#170947422 configure ESlint and babel
andela/octopus-bn-backend pull request #1
Opened 2020-02-04 13:10 UTC by AbdoulNuru

#### What does this PR do?
Have eslint and babel configured.

#### Description of Task to be completed?
- Configure eslint to lint our codes using airbnb as the style guide and all the predefined rules
- Configure babel to convert our ES6 code to the compatible version which is ES5

#### How should this be manually tested?
- Use `git clone <repo link>` to clone the repo to your local machine
- Use `npm i` to install all the project dependencies
- Run `npm run lint` to have eslint report problems, warnings and errors in your code
- Run `npm run lintFix` to have eslint fix all auto fixable problems.

#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
[#170947422](https://www.pivotaltracker.com/story/show/170947422)
#### Screenshots (if appropriate)
<img width="834" alt="Screen Shot 2020-02-04 at 14 11 04" src="https://user-images.githubusercontent.com/53453380/73746216-6168a500-475d-11ea-9d46-21e3e85fa02f.png">
<img width="415" alt="Screen Shot 2020-02-04 at 14 11 28" src="https://user-images.githubusercontent.com/53453380/73746229-64639580-475d-11ea-89b8-25224b6b2a55.png">

#### Questions:

2020-02-04 13:18 UTC, RusimbiPatrick reviewed
Check out the ESlint new line problem

2020-02-04 13:24 UTC, izzett222 requested changes

2020-02-04 13:24 UTC, izzett222 commented on .eslintrc.json
> +      "requireReturnDescription": true
hey @AbdoulNuru , the eslint rules above have different indentation

2020-02-04 13:34 UTC, AbdoulNuru commented on .eslintrc.json
> +      "requireReturnDescription": true
@izzett222 Because some of them are nested inside the other.

2020-02-04 13:36 UTC, hakoemmy approved these changes

2020-02-04 13:39 UTC, izzett222 commented on .eslintrc.json
> +      "requireReturnDescription": true
that's true, but apart from the first rules, the others don't have any indentation at all.

2020-02-04 13:46 UTC, AbdoulNuru commented
> Check out the ESlint new line problem

@RusimbiP It was a mistake but I fixed it you can check now, thank you for noticing

2020-02-04 13:53 UTC, blaise82 commented
just a question do we need to add screenshots of our code too (in the PR description)?

for I don't think that code Screenshots are appropriate

2020-02-04 13:55 UTC, RusimbiPatrick commented
> just a question do we need to add screenshots of our code too (in the PR description)?

I think it would be helpful.

2020-02-04 13:57 UTC, AbdoulNuru commented on .eslintrc.json
> +      "requireReturnDescription": true
@izzett222 I have realized that some rules were not indented correctly and I fixed it, Thanks.

2020-02-04 13:57 UTC, izzett222 approved these changes

2020-02-04 13:58 UTC, RusimbiPatrick approved these changes

2020-02-04 14:01 UTC, AbdoulNuru commented
> just a question do we need to add screenshots of our code too (in the PR description)?
> 
> for I don't think that code Screenshots are appropriate

@blaise82 I added them because I think they are helpful, but am not sure if it's appropriate or not, maybe our TTL will help us with this one.

2020-02-04 14:02 UTC, hakoemmy commented
> just a question do we need to add screenshots of our code too (in the PR description)?
> 
I think adding screenshots of code is a kind of messy when you have written lots of code but there is no problem with chores.

2020-02-04 14:04 UTC, blaise82 commented
> > just a question do we need to add screenshots of our code too (in the PR description)?
> 
> I think adding screenshots of code is a kind of messy when you have written lots of code but there is no problem with chores.

I don't think it's appropriate because if I wanted to know what he changed i could just check 
and in the screenshots, it's harder to know what's new and what's old

2020-02-04 14:06 UTC, hakoemmy commented
> > > just a question do we need to add screenshots of our code too (in the PR description)?
> > 
> > 
> > I think adding screenshots of code is a kind of messy when you have written lots of code but there is no problem with chores.
> 
> I don't think it's appropriate because if I wanted to know what he changed i could just check
> and in the screenshots, it's harder to know what's new and what's old

>>
> Sure. When you are working on a feature you better attach postman screenshots

2020-02-04 14:11 UTC, blaise82 commented
maybe one/two important things he might have forgotten is adding build and eslint fix commands to package.json

2020-02-04 16:12 UTC, AbdoulNuru commented
@blaise82 am not sure about that

2020-02-05 06:51 UTC, blaise82 commented
> @blaise82 am not sure about that

morning
about?

2020-02-05 08:41 UTC, blaise82 approved these changes

2020-02-05 11:03 UTC, kcharles52 requested changes
Please create a script in the package.json file with a name and can just be run with `npm run <script-name>`
Example
under scripts on package.json file add something like this
`"lint":"command to run linting with eslint"`
such that we only have to type `npm lint or npm run lint`

2020-02-05 11:29 UTC, kcharles52 approved these changes
Welldone

2020-02-05 11:31 UTC, merged