#170947429 setup swagger
andela/octopus-bn-backend pull request #10
Opened 2020-02-06 10:53 UTC by AbdoulNuru

#### What does this PR do?
setup api documentation using swagger

#### Description of Task to be completed?
- setup swagger for auto-documentation using jsdoc

#### How should this be manually tested?
- Use `git clone <repo link>` to clone the repo to your local machine
- Use `npm i` to install all the project dependencies
- Run `npm run dev` to start the development server
- access the documentation on this Link ```http://localhost:3000/api-docs/```

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#170947429](https://www.pivotaltracker.com/story/show/170947429)

#### Screenshots (if appropriate)
<img width="1195" alt="Screen Shot 2020-02-06 at 12 46 29" src="https://user-images.githubusercontent.com/53453380/73930146-bc75d580-48de-11ea-92d0-01c02921b703.png">

#### Questions:
N/A

2020-02-06 11:11 UTC, izzett222 approved these changes

2020-02-06 11:11 UTC, hakoemmy approved these changes

2020-02-06 11:54 UTC, blaise82 approved these changes

2020-02-06 16:00 UTC, RusimbiPatrick approved these changes

2020-02-07 06:57 UTC, kcharles52 requested changes

2020-02-07 06:57 UTC, kcharles52 commented on src/routes/api/index.js
> +import Router from 'express';
```suggestion
import { Router } from 'express';
```
Check other files for the same

2020-02-07 06:57 UTC, kcharles52 commented on src/utils/api-specifications.js
> +        url: `https://${process.env.HEROKU_APP_NAME}.herokuapp.com`,
Look at these resources 
https://nodejs.org/api/os.html#os_os_hostname
https://www.codota.com/code/javascript/functions/os/hostname
https://www.w3schools.com/nodejs/ref_os.asp

2020-02-07 07:54 UTC, kcharles52 approved these changes

2020-02-07 11:56 UTC, merged