#170947432 Integrate JSON web token
andela/octopus-bn-backend pull request #14
Opened 2020-02-11 09:10 UTC by hakoemmy

#### What does this PR do?
- Have JSON web token integrated
#### Description of Task to be completed?
 -  Add ``jsonwebtoken`` module
- Add encode function
- Add decode function
#### How should this be manually tested?

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#170947432](https://www.pivotaltracker.com/story/show/170947432)
### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2020-02-12 11:10 UTC, AbdoulNuru approved these changes

2020-02-12 11:14 UTC, blaise82 approved these changes

2020-02-12 12:59 UTC, RusimbiPatrick approved these changes

2020-02-12 14:16 UTC, izzett222 approved these changes

2020-02-13 09:21 UTC, kcharles52 requested changes

2020-02-13 09:21 UTC, kcharles52 commented on src/utils/jwtTokenizer.js
> +export const encode = (claims) => {
add documentation

2020-02-13 10:09 UTC, kcharles52 approved these changes

2020-02-13 10:11 UTC, merged