#170947435 Build sign-in feature
andela/octopus-bn-backend pull request #16
Opened 2020-02-11 12:05 UTC by RusimbiP

### What does this PR do?

- Have sign-in feature build
- Have sign-in feature tested

### How should this be manually tested?

- Clone the [repo](https://github.com/andela/octopus-bn-backend.git)
- Run ``` npm install ```
-  Hit `http://localhost:3000/api/v1/auth/signin` to test it.

### Implementation plan

[Implementation plan name](https://drive.google.com/drive/u/1/folders/10O6cku3mfx2EQjTnghkYTr4tixe8xe-A)

### Stories associated with PR

[##170947435](https://www.pivotaltracker.com/story/show/170947435)

### Screenshots if any
<img width="1118" alt="Screen Shot 2020-02-11 at 13 20 11" src="https://user-images.githubusercontent.com/54870069/74234308-2de5c780-4cd5-11ea-96be-24be8e69c30c.png">

2020-02-12 11:28 UTC, blaise82 approved these changes

2020-02-12 12:11 UTC, hakoemmy approved these changes

2020-02-12 12:46 UTC, izzett222 approved these changes

2020-02-13 09:59 UTC, kcharles52 requested changes

2020-02-13 09:59 UTC, kcharles52 commented on src/controllers/user.controller.js
> +import service from '../services/user.services';
```suggestion
import service from '../services/userServices';
```

2020-02-13 09:59 UTC, kcharles52 commented on src/database/migrations/20200206093213-create-users.js
> +};
```suggestion
};

```

2020-02-13 09:59 UTC, kcharles52 commented on src/routes/api/user.routes.js
> +import userController from '../../controllers/user.controller';
```suggestion
import userController from '../../controllers/userController';
```

2020-02-13 09:59 UTC, kcharles52 commented on src/routes/api/user.routes.js
> +router.post('/signin', userController.signin);
```suggestion
router.post('/signin', userController.signin);

```

2020-02-13 09:59 UTC, kcharles52 commented on src/routes/api/user.routes.js
> +
```suggestion
```

2020-02-13 09:59 UTC, kcharles52 commented on src/services/user.services.js
> +/* eslint-disable require-jsdoc */
```suggestion

```

2020-02-13 09:59 UTC, kcharles52 commented on src/services/user.services.js
> +class userService {
add documentation for the class and methods

2020-02-13 09:59 UTC, kcharles52 commented on src/services/user.services.js
> +      if (method !== 'local') {
```suggestion
      
      if (method !== 'local') {
```

2020-02-13 09:59 UTC, kcharles52 commented on src/test/signin.test.js
> +  it('It should show an error if the uses uses Open Auth', (done) => {
check the grammar used in the test description

2020-02-13 15:00 UTC, AbdoulNuru approved these changes

2020-02-14 06:39 UTC, kcharles52 approved these changes

2020-02-14 06:50 UTC, merged