#170947434 user inputs validation
andela/octopus-bn-backend pull request #17
Opened 2020-02-11 21:05 UTC by izzett222

#### What does this PR do?
add user inputs validation feature
#### Description of Task to be completed?
- install express-validator
- added the validation middleware
- added validation middleware tests
#### How should this be manually tested?
- clone this repo
- run npm install
- set up database (see readme)
- run npm run seedDb
- run npm run dev
- access the signup endpoint(/api/v1/auth/signup) through postman
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#170947434
#### Screenshots (if appropriate)
#### Questions:- added the user route file

2020-02-12 11:05 UTC, AbdoulNuru approved these changes

2020-02-12 11:08 UTC, hakoemmy approved these changes

2020-02-12 11:29 UTC, blaise82 approved these changes

2020-02-12 11:37 UTC, RusimbiPatrick requested changes
In the case of error messages, The status code should be 422(unprocessable entity) instead of 400(bad request)
**Example**
<img width="1440" alt="Screen Shot 2020-02-12 at 13 38 21" src="https://user-images.githubusercontent.com/54870069/74332076-b3cd4580-4d9d-11ea-840f-e5229e37793d.png">

2020-02-12 13:39 UTC, izzett222 commented
> In the case of error messages, The status code should be 422(unprocessable entity) instead of 400(bad request)
> **Example**
> <img alt="Screen Shot 2020-02-12 at 13 38 21" width="1440" src="https://user-images.githubusercontent.com/54870069/74332076-b3cd4580-4d9d-11ea-840f-e5229e37793d.png">

I changed the status code to 422

2020-02-12 13:39 UTC, RusimbiPatrick approved these changes

2020-02-12 13:40 UTC, RusimbiPatrick approved these changes

2020-02-13 09:50 UTC, kcharles52 requested changes

2020-02-13 09:50 UTC, kcharles52 commented on src/routes/api/user.routes.js
> +router.post('/signup', checkFirstName, checkLastName, checkValidEmail, checkExistingEmail, checkPassword, validateResult);
```suggestion

router.post('/signup', checkFirstName, checkLastName, checkValidEmail, checkExistingEmail, checkPassword, validateResult);
```
Add space after constants

2020-02-13 09:50 UTC, kcharles52 commented on package.json
> +    "test": "NODE_ENV=test npm run migrateTest && NODE_ENV=test nyc --reporter=html --reporter=text mocha  --require @babel/polyfill --require @babel/register 'src/**/**test.js'  --timeout 200000 --e
```suggestion
    "test": "NODE_ENV=test npm run migrateTest &&  nyc --reporter=html --reporter=text mocha  --require @babel/polyfill --require @babel/register 'src/**/**test.js'  --timeout 200000 --exit",
```

2020-02-13 12:05 UTC, merged