#170947439 Add profile settings
andela/octopus-bn-backend pull request #23
Opened 2020-02-18 17:28 UTC by hakoemmy

### What does this PR do?
- Add ``gender, birthDate, preferedLang, preferedCurrency, residence, department, managerEmail, imageUrl`` and ``bio``columns to ``Users`` model
- Allow user to edit his/her own profile

### How should this be manually tested?

- Just clone the [repo](https://github.com/andela/octopus-bn-backend.git)
- Run `` npm i`` to install depedencies
- Run ``npm run dev`` to start local server
- Then launch postman and hit send to this route:```localhost:3000/api/v1/auth/profile-settings```

### Implementation plan

[Profile settings implementation plan](https://docs.google.com/document/d/1JIO6SDS2mjiXfhLEDWZSoG1XLy7_RMmXejG6IAl2pU4/edit?usp=sharing)

### Stories associated with PR

[#170947439](https://www.pivotaltracker.com/story/show/170947439)

### Screenshots if any

<img width="1064" alt="Screen Shot 2020-02-18 at 19 27 29" src="https://user-images.githubusercontent.com/51243858/74761462-c1466c00-5284-11ea-8965-1c20db2dbd7d.png">

2020-02-19 08:42 UTC, blaise82 approved these changes

2020-02-19 08:42 UTC, RusimbiPatrick approved these changes

2020-02-19 08:48 UTC, blaise82 requested changes

2020-02-19 08:48 UTC, blaise82 commented on locales/[object Promise].js
> +}
```suggestion
}

```
add a new line

2020-02-19 09:04 UTC, blaise82 approved these changes

2020-02-20 06:20 UTC, AbdoulNuru approved these changes

2020-02-20 09:53 UTC, kcharles52 approved these changes

2020-02-20 09:55 UTC, merged