feat(trips): get all trip requests
andela/octopus-bn-backend pull request #30
Opened 2020-02-24 09:21 UTC by blaise82

### What does this PR do?

- create GET request route
- create get request method in the trip controller
- write tests

### How should this be manually tested?

- clone this repo using `git clone https://github.com/andela/octopus-bn-backend`
- run `cd octopus-bn-backend` to move to the directory
- run `npm install` to install all required dependencies
- run `npm run dev` to start the development server
- open postman GET localhost:3000/api/v1/trips/request

### Implementation plan
[Integrate the requests table to the backend](https://docs.google.com/document/d/1k32rRF6f1LAUQPGX5IvHRH0mPTb51qzFUDkWe_ZZEA8/edit)

### Screenshots if any
<img width="1440" alt="Screen Shot 2020-02-24 at 11 15 10" src="https://user-images.githubusercontent.com/52036624/75140495-b31aa480-56f7-11ea-9817-c8f3153c4dcf.png">

[finishes #170947444]

2020-02-24 12:07 UTC, hakoemmy requested changes

2020-02-24 12:07 UTC, hakoemmy commented on locales/en.js
> +}
```suggestion
}

```

2020-02-24 12:07 UTC, hakoemmy commented on locales/en.json
> +}
```suggestion
}

```

2020-02-24 12:07 UTC, hakoemmy commented on locales/fr.js
> +}
```suggestion
}

```

2020-02-24 12:07 UTC, hakoemmy commented on locales/fr.json
> +}
```suggestion
}

```

2020-02-24 12:07 UTC, hakoemmy commented on src/controllers/tripsController.js
> +      return successResponse(res, 200, req.i18n.__('retrievedSuccessfully'), trips);
```suggestion
      return successResponse(res, 200, setLanguage(req.user.preferedLang).__('retrievedSuccessfully'), trips);
```
@blaise82  I think that you'll have to keep track of translation basing on the user's preference when my PR is probably merged.

2020-02-24 12:07 UTC, hakoemmy commented on src/controllers/tripsController.js
> +      return errorResponse(res, error.status || 500, error.message);
```suggestion
      return errorResponse(res, error.status || 500, setLanguage(req.user.preferedLang).__('internalServerError'));
```
Would you please consider returning a specific message to a user other than server default errors?
The locale for ```internalServerError``` key has been already set.

2020-02-24 12:07 UTC, hakoemmy commented on src/middlewares/tripRequestDateValidator.js
> +      message: req.i18n.__('validReturnDate')
```suggestion
      message: setLanguage(req.user.preferedLang).__('validReturnDate')
```

2020-02-24 12:07 UTC, hakoemmy commented on src/middlewares/tripRequestValidator.js
>    });
When my PR is merged. make use of ```setLanguage(req.user.preferedLang).__('YourKey')```

2020-02-24 12:07 UTC, hakoemmy commented on src/routes/api/trips.routes.js
> +router.get('/request', checkUser, tripsController.getTrips);
@blaise82  I've created middleware called ```isProfileUpdated.js```. You must accept it While you'll be rebasing.

2020-02-24 12:07 UTC, hakoemmy commented on src/routes/api/trips.routes.js
> +router.get('/request', checkUser, tripsController.getTrips);
```suggestion
router.get('/', checkUser, tripsController.getTrips);
```
Just a suggestion, I know in the creation of a one-way trip request you are using ```/request``` but if you change  GET request to ```/api/v1/trips``` that would look nice.

2020-02-24 12:11 UTC, blaise82 commented on src/controllers/tripsController.js
> +      return successResponse(res, 200, req.i18n.__('retrievedSuccessfully'), trips);
that haven't been merged
so I don't think it applies now

2020-02-24 12:14 UTC, blaise82 commented on src/controllers/tripsController.js
> +      return errorResponse(res, error.status || 500, error.message);
That sounds better

2020-02-24 12:19 UTC, hakoemmy approved these changes

2020-02-24 12:19 UTC, hakoemmy commented on src/controllers/tripsController.js
> +      return successResponse(res, 200, req.i18n.__('retrievedSuccessfully'), trips);
@blaise82 For sure. You'll address these changes when this [PR](https://github.com/andela/octopus-bn-backend/pull/28) is merged.

2020-02-24 13:18 UTC, RusimbiPatrick approved these changes

2020-02-25 17:10 UTC, AbdoulNuru approved these changes

2020-02-26 08:08 UTC, kcharles52 approved these changes

2020-02-26 08:09 UTC, merged