chore(response): refactor response objects
andela/octopus-bn-backend pull request #62
Opened 2020-03-23 14:37 UTC by AbdoulNuru

### What does this PR do?

- Refactor the response objects
- fix the existing vulnerability on the main branch

### How should this be manually tested?

- clone this repo by running `git clone <repo link>` in your terminal
- switch to this branch `ch-refactor-response-objects-171922008` by running `git checkout <branch name>` in your terminal.
- referencing `.env.example` file, create a `.env` file and add all required variables.
- run the migrations using this command `npm run migrateDb`.
- start the development server using this command `npm run dev`.
- using postman login using this route *POST*`localhost:3000/api/v1/auth/signin`, you will need to provide an *email* and a *password*.
- in postman, use this route *GET* `localhost:3000/api/v1/accommodations/*id*` to get the details of particular accommodation, you will need to provide the *accommodation id*.

### Implementation plan

[Implementation plan](https://)

### Stories associated with PR

[#171922008](https://www.pivotaltracker.com/story/show/171922008)

### Screenshots if any
<img width="471" alt="Screen Shot 2020-03-23 at 15 19 05" src="https://user-images.githubusercontent.com/53453380/77327452-ef0b4e80-6d23-11ea-88a8-a0bd3e09f4bb.png">
<img width="1139" alt="Screen Shot 2020-03-23 at 16 31 42" src="https://user-images.githubusercontent.com/53453380/77327461-f29ed580-6d23-11ea-81b8-f45e75ba7ba7.png">

2020-03-23 17:34 UTC, blaise82 approved these changes

2020-03-23 17:38 UTC, blaise82 reviewed
if possible would u also take a look at what's returned when 
someone get's one trip requests 

and return comments and users object on the comments too

2020-03-24 08:54 UTC, hakoemmy approved these changes

2020-03-24 09:57 UTC, AbdoulNuru commented
> if possible would u also take a look at what's returned when
> someone get's one trip requests
> 
> and return comments and users object on the comments too

The comment was returned so I just added the user object too

2020-03-24 10:56 UTC, blaise82 approved these changes

2020-03-24 18:45 UTC, RusimbiPatrick requested changes
Include trip id after creating a trip request.

2020-03-27 10:11 UTC, RusimbiPatrick approved these changes

2020-03-27 13:30 UTC, merged